### ISSUE TITLE
Aeon#7201 | A "Veto" feature.

### ISSUE THREAD

**Issue by GoogleFormsSubmission** [That-Bot-Development/ThatBot-Issues#41]
**Describe the Feature:** A feature that behaves similarly to the "NO" card, for fun. Upon using "^Veto <user>", the bot should respond with a message saying: "@user, you have been Vetoed." Vetoes should be bought in the store, and used up after the ^veto command has been used.

**Comment by Zach-2000** [comment]
Community Review - Suggestion will be evaluated via a server poll.

**Comment by Zach-2000** [comment]
[Update] Accepted - Will be added in 1.2.7.

**Comment by Zach-2000** [comment]
[Update] Denied - Unfortunately after further review, this feature will not be added at this time.
