### ISSUE TITLE
Nice#4269 | Typing "Spin", "Speen" or something else similar should make the bot send the :speeeeen: emoji

### ISSUE THREAD

**Issue by GoogleFormsSubmission** [That-Bot-Development/ThatBot-Issues#43]
**Describe the Feature:** Pretty much all in the title but yeah. Basically the same as the "funny plane" suggestion.

**Comment by Zach-2000** [comment]
Accepted - Will be added in 1.2.7.

**Comment by Zach-2000** [comment]
Modified - Moved to version 1.3.

**Comment by Zach-2000** [comment]
Complete - This feature has been implemented.
