### ISSUE TITLE
Matix777#4898 | Make That Bot give like/dislike reaction to every song posted in #music

### ISSUE THREAD

**Issue by GoogleFormsSubmission** [That-Bot-Development/ThatBot-Issues#45]
**Describe the Feature:** When Bot would see a link in #music it would immediately give it like/dislike reaction, so people could vote on if they like the song or not (totaly not made beacuse i want to boost my ego by seeing that people actually listened to my song)

**Comment by Zach-2000** [comment]
Accepted - Will be added in 1.3.

**Comment by Zach-2000** [comment]
Complete - This feature has been implemented.
