### ISSUE TITLE
Aeon#7201 | When someone says Gas, react with wind emoji.

### ISSUE THREAD

**Issue by GoogleFormsSubmission** [That-Bot-Development/ThatBot-Issues#52]
**Describe the Feature:** When someone says Gas/Fart react with :wind_blowing_face:

**Comment by possiblyamagicmage** [comment]
yes

**Comment by Zach-2000** [comment]
Accepted - Will be added in 1.3.

**Comment by Zach-2000** [comment]
Complete - This feature has been implemented.
