### ISSUE TITLE
Rifter#0160 | ^pet, ^pat, and ^hug no longer work

### ISSUE THREAD

**Issue by GoogleFormsSubmission** [That-Bot-Development/ThatBot-Issues#53]
**Describe the Bug:** The ^pet, ^pat, and ^hug no longer work as the bot that is supposed to take in these commands (f!pet, f!pat, f!hug) is no longer in the server.
**Describe how to Reproduce:** Go to #bot-stuff and type in ^pet, ^pat, or ^hug. The bot sends the f!command, but nothing else happens.
**Describe the Expected Behavior:** Most likely, a bot would accept these f!commands and accept the pet, pat, or hug. Unfortunately, these commands will remain without any use while the bot is not here.
(Optional) **Add any Additional Info:** I have tried these commands myself, still nothing.

**Comment by notvelleda** [comment]
lmao the bot's just offline, it'll be fixed Soon™

**Comment by Zach-2000** [comment]
Denied - As velleda stated, the bot is simply offline and will presumably come online again at some point in the future.
