### ISSUE TITLE
Rifter#0160 | gnap

### ISSUE THREAD

**Issue by GoogleFormsSubmission** [That-Bot-Development/ThatBot-Issues#54]
**Describe the Feature:** When the following message is typed:
"@DefinedElf908#9008 RULES!!!" (i dont know how discord syntax works)
That Bot can react one of these emotes:
:rules:, :feesh:, :puddle:, :yoooo:, :noooo:, :fishsquish:
these are all vaporeon emotes thank you

**Comment by possiblyamagicmage** [comment]
HELL YEAH

**Comment by Zach-2000** [comment]
Denied - Doesn't seem like something that will be used often.
