### ISSUE TITLE
PossiblyAMagicMage#6028 | Time Converter

### ISSUE THREAD

**Issue by GoogleFormsSubmission** [That-Bot-Development/ThatBot-Issues#57]
**Describe the Feature:** Using a command, for example, ^time [time] [12hour/24hour] [am/pm] [originaltimezone] [newtimezone] would convert the time specified in [time] and if [12hour/24hour] is 12, use [AM/PM] from the original timezone [originaltimezone] (for example PST) to the new timezone [newtimezone] (for example GMT+5) then say the time converted.
Example: ^time 19:35 24h GMT+5 GMT+4
That Bot: 19:35 in GMT+5 (24 hour format) is 18:35 in GMT+4.

**Comment by possiblyamagicmage** [comment]
very clear and concise

**Comment by Zach-2000** [comment]
Suspended - This suggestion will not be implemented at this time, but may be reevaluated at a later date.

**Comment by Zach-2000** [comment]
Denied - This suggestion will not be implemented.
