### ISSUE TITLE
NEO Pico | Incin Corp#4374 | Bot to ping users shinyhunting

### ISSUE THREAD

**Issue by GoogleFormsSubmission** [That-Bot-Development/ThatBot-Issues#60]
**Describe the Feature:** A bot that pings a person shinyhunting a pokemon, like the Sierra bot I think, so anyone shinyhunting has a higher chance of extending their chain

**Comment by possiblyamagicmage** [comment]
maybe something like ^sh <pokedex_id> then you are pinged whenever that pokemon appears in shiny form? except the bot would have to manually scan each image and determine if it's the right pokemon

**Comment by Zach-2000** [comment]
Staff Review - This suggestion will be reviewed by staff who are more familiar with Pokemon Bots.

**Comment by Zach-2000** [comment]
Denied - This suggestion will not be implemented into That Bot as it would be low priority and therefore would take a long time, however, the Sierra bot may be added to do this exact thing instead.
