### ISSUE TITLE
Rifter#0160 | autoreacts :flushed:

### ISSUE THREAD

**Issue by GoogleFormsSubmission** [That-Bot-Development/ThatBot-Issues#65]
**Describe the Feature:** "In all seriousness turn this into an autoreact with ':flushed:'" -rifter
typing "butts" autoreacts :flushed:
why? scroll up and find my thing which i had to create a github account to post

**Comment by rifterrrrrrrrrr** [comment]
when bot-suggestions dies

**Comment by Zach-2000** [comment]
Denied - This suggestion will not be implemented.

**Comment by Zach-2000** [comment]
Denied - This suggestion will not be implemented.

**Comment by Zach-2000** [comment]
Denied - This suggestion will not be implemented.
