### ISSUE TITLE
Rifter#0160 | have a backup bot handy

### ISSUE THREAD

**Issue by GoogleFormsSubmission** [That-Bot-Development/ThatBot-Issues#75]
**Describe the Feature:** The bot goes down a lot, and I mean a lot, so PLEASE have another bot that is identical to the main bot in every way, but is only on when the main bot is down.
Unless this is impossible.

**Comment by Zach-2000** [comment]
Denied - The reason why the bot goes down so much is because it is hosted off of my PC. I have a better solution for this problem involving using a different machine to host the bot, I just have to actually get it done haha.
